#!/bin/bash
i=0
adresses=(192.168.0.1 173.194.222.113 87.250.250.242)
echo ${adresses[1]}
while [ $i != 5 ]; do
  for ip in ${adresses[@]}; do
    nc -z $ip 80
    echo "Результат $ip - $?" >> log.txt
  done

#  array=("Результат 192.168.0.1 - ${host1}"
#         "Результат 173.194.222.113 - ${host2}"
#         "Результат 87.250.250.242 - ${host3}")
#  for el in "${array[@]}"; do
#    echo $el >> log.txt
#  done
  ((i+=1))
done