#!/bin/bash
host1=192.168.0.1
host2=173.194.222.113
host3=87.250.250.242
while [ 1 = 1 ]; do

  nc -z 173.194.222.113 80
  if (($? != 0)); then
    echo $host2 >> log.log
    break
  fi

  nc -z 87.250.250.242 80
  if (($? != 0)); then
    echo $host3 >> log.log
    break
  fi

  nc -z localhost 5001
  if (($? != 0)); then
    echo $host1 >> log.log
    break
  fi

done