#!/bin/bash
i=0
adresses=(192.168.0.1 173.194.222.113 87.250.250.242)

while [ $i != 5 ]; do
  for ip in ${adresses[@]}; do
    nc -z $ip 80
    echo "Результат $ip - $?" >> log.txt
  done

  ((i+=1))
done