#!/bin/bash

adresses=(173.194.222.113 87.250.250.242 192.168.0.1)
is_bad_connection=False

while [ $is_bad_connection = False ]; do

  for ip in ${adresses[@]}; do
    nc -z $ip 80

    if (($? != 0)); then
      echo $ip >> log.log
      is_bad_connection=True
    fi

  done

done