#!/bin/bash
i=0
while [ $i != 5 ]; do
  nc -z 192.168.0.1 80
  host1=$?
  nc -z 173.194.222.113 80
  host2=$?
  nc -z 87.250.250.242 80
  host3=$?
  array=("Результат 192.168.0.1 - ${host1}"
         "Результат 173.194.222.113 - ${host2}"
         "Результат 87.250.250.242 - ${host3}")
  for el in "${array[@]}"; do
    echo $el >> log.txt
  done
  ((i+=1))
done