apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pvc
  namespace: default
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi