apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front
  name: front
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - image: praqma/network-multitool:alpine-extra
          imagePullPolicy: IfNotPresent
          name: network-multitool
          env:
            - name: back_adress
              value: "10.233.33.107"
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: prod
spec:
  ports:
    - name: web
      port: 80
  selector:
    app: front
