apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    env: stage
  name: stage
  namespace: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      env: stage
  template:
    metadata:
      labels:
        env: stage
    spec:
      containers:
        - image: praqma/network-multitool:alpine-extra
          imagePullPolicy: IfNotPresent
          name: back
          env:
          - name: HTTP_PORT
            value: "8080"
        - image: nginx:1.20
          imagePullPolicy: IfNotPresent
          name: front
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: stage
  namespace: stage
spec:
  ports:
    - name: web
      port: 80
  selector:
    env: stage
