apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    env: stage
  name: stage
  namespace: 132stage
spec:
  replicas: 1
  selector:
    matchLabels:
      env: stage
  template:
    metadata:
      labels:
        env: stage
    spec:
      containers:
        - image: praqma/network-multitool:alpine-extra
          imagePullPolicy: IfNotPresent
          name: back
          env:
            - name: HTTP_PORT
              value: "8080"
          volumeMounts:
            - mountPath: "/back"
              name: stage-volume
        - image: nginx:1.20
          imagePullPolicy: IfNotPresent
          name: front
          volumeMounts:
            - mountPath: "/front"
              name: stage-volume
      terminationGracePeriodSeconds: 30
      volumes:
        - name: stage-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: stage
  namespace: 132stage
spec:
  ports:
    - name: web
      port: 80
  selector:
    env: stage
