---
all:
  hosts:
    jenkins-master-01:
      ansible_host: '178.154.247.1'
    jenkins-agent-01:
      ansible_host: '178.154.227.78'
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: ssh
    ansible_user: centos