apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front
  name: front
  namespace: 132prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - image: praqma/network-multitool:alpine-extra
          imagePullPolicy: IfNotPresent
          name: network-multitool
          volumeMounts:
            - mountPath: "/front"
              name: prod-volume
      volumes:
        - name: prod-volume
          persistentVolumeClaim:
            claimName: prod-pvc
      terminationGracePeriodSeconds: 30


---
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: 132prod
spec:
  ports:
    - name: web
      port: 80
  selector:
    app: front
