apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-pvc
  namespace: 132prod
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi