all:
  hosts:
    cp1:
      ansible_host: 51.250.70.231
      ansible_user: ubuntu
    worker1:
      ansible_host: 51.250.65.53
      ansible_user: ubuntu
    worker2:
      ansible_host: 51.250.76.235
      ansible_user: ubuntu
    worker3:
      ansible_host: 51.250.94.130
      ansible_user: ubuntu
    worker4:
      ansible_host: 51.250.95.170
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        worker1:
        worker2:
        worker3:
        worker4:
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
