apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: netology
spec:
  environments:
    default:
      defaultNamespace: default
      server: https://51.250.88.173:6443
    stage:
      defaultNamespace: stage
      server: https://51.250.88.173:6443
      excludes:
        - ep
    production:
      defaultNamespace: production
      server: https://51.250.88.173:6443
  vars: {}
